server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.records: 1
        fetch.min.bytes: 1
        fetch.max.wait.ms: 100
  mail:
    host: localhost
    port: 1025
    username:
      password:
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: false
            starttls:
              enable: false
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
      default-encoding: UTF-8

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        display-request-duration: true
        try-it-out-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    healthcheck:
      enabled: true
  instance:
      hostname: discovery-service
      prefer-ip-address: false
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.example: INFO
    org.springframework.kafka: DEBUG
    org.springframework.cloud: DEBUG