server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    healthcheck:
      enabled: true
  instance:
      hostname: discovery-service
      prefer-ip-address: false
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.example: INFO
    org.springframework.kafka: DEBUG
    org.springframework.cloud: DEBUG